config/routes.rb
Rails.application.routes.draw do
  resources :orders do
    member do
      post 'open'
      post 'close'
    end
  end

  resources :items
  resources :restaurants

  root 'population_process#index'
  get  'admin' => 'admin#index', as: :admin

  post   'add_item'             => 'main#add_item',    as: :add_item
  delete 'delete_item/:item_id' => 'main#delete_item', as: :delete_item
  get    'typehead'             => 'main#typehead',    as: :typehead

  post 'user/login'  => 'user#login',    as: :user_login
  post 'user/logout' => 'user#logout',   as: :user_logout


  get  'population'         => 'population_process#index',   as: :population_process_index
  post 'population/root'    => 'population_process#root',    as: :population_process_root
  post 'population/general' => 'population_process#general', as: :population_process_general
  post 'population/age_range'      => 'population_process#age_range',      as: :population_process_age_range
  post 'population/root_couple'    => 'population_process#root_couple',    as: :population_process_root_couple
  post 'population/general_couple' => 'population_process#general_couple', as: :population_process_general_couple

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)



  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :restaurant

  has_many :items

  validates :description, :order_at, :restaurant_id, presence: true

  include AASM

  aasm do
    state :draft, :initial => true
    state :active
    state :archive

    event :open do
      transitions :to => :active
    end

    event :close do
      transitions :from => :active, :to => :archive
    end
  end

  def state_humanize
    name_mapping = {
      'draft'   => '草稿',
      'active'  => '上架中',
      'archive' => '已下架',
    }

    name_mapping[aasm_state]
  end

  def title
    "#{order_at.strftime('%m/%d %a')} #{description}"
  end
end

app/controllers/orders_controller.rb
class OrdersController < Admin::ApplicationController
  layout 'admin'

  before_action :set_order, only: [:show, :edit, :update, :destroy, :open, :close]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def open
    @order.open!
    redirect_to orders_url
  end

  def close
    @order.close!
    redirect_to orders_url
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:description, :restaurant_id, :order_at, :aasm_state, :handler)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(@order, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @order.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h4>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :description, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :restaurant_id, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select(:restaurant_id, Restaurant.all.collect {|r| [ r.name, r.id ] }, { include_blank: false }, class: "form-control") %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :order_at, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.datetime_select :order_at, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :handler, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :handler, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/orders/edit.html.erb
<div class="page-header">
  <%= link_to orders_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @order, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing order</h1>
</div>

<%= render 'form' %>

app/views/orders/index.html.erb
<div class="page-header">
  <%= link_to new_order_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Order
  <% end %>
  <h1>Listing orders</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Description</th>
            <th>Restaurant</th>
            <th>Order at</th>
            <th>狀態</th>
            <th>Handler</th>
            <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @orders) do |order| %>
            <td><%= order.description %></td>
            <td><%= order.restaurant_id %></td>
            <td><%= order.order_at %></td>
            <td>
              <span class="label
<% case order.aasm_state %>
<% when 'draft' %>
  label-default
<% when 'active' %>
  label-success
<% when 'archive' %>
  label-danger
<% end %>
              ">
                <%= order.state_humanize %>
              </span>

            </td>
            <td><%= order.handler %></td>
            <td class="text-right">
<% case order.aasm_state %>
<% when 'draft' %>
  <%= link_to '上架', open_order_path(order), class:  "btn btn-success", method: :post %>
<% when 'active' %>
  <%= link_to '下架', close_order_path(order), class:  "btn btn-danger", method: :post, data: { confirm: 'Are you sure?' } %>
<% when 'archive' %>
  <%= link_to '上架', open_order_path(order), class:  "btn btn-success", method: :post %>
<% end %>
              <div class="btn-group" role="group" aria-label="...">
                <%= link_to 'Show', order, class:  "btn btn-default" %>
                <%= link_to 'Edit', edit_order_path(order), class:  "btn btn-default" %>
                <%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' }, class:  "btn btn-default" %>
              </div>
            </td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/orders/new.html.erb
<div class="page-header">
  <%= link_to orders_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New order</h1>
</div>

<%= render 'form' %>

app/views/orders/show.html.erb
<div class="page-header">
  <%= link_to orders_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_order_path(@order), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show order</h1>
</div>

<dl class="dl-horizontal">
  <dt>Description:</dt>
  <dd><%= @order.description %></dd>

  <dt>Restaurant:</dt>
  <dd><%= @order.restaurant_id %></dd>

  <dt>Order at:</dt>
  <dd><%= @order.order_at %></dd>

  <dt>Aasm state:</dt>
  <dd><%= @order.aasm_state %></dd>

  <dt>Handler:</dt>
  <dd><%= @order.handler %></dd>

</dl>