config/routes.rb
Rails.application.routes.draw do
  resources :orders do
    member do
      post 'open'
      post 'close'
    end
  end

  resources :items
  resources :restaurants

  root 'population_process#index'
  get  'admin' => 'admin#index', as: :admin

  post   'add_item'             => 'main#add_item',    as: :add_item
  delete 'delete_item/:item_id' => 'main#delete_item', as: :delete_item
  get    'typehead'             => 'main#typehead',    as: :typehead

  post 'user/login'  => 'user#login',    as: :user_login
  post 'user/logout' => 'user#logout',   as: :user_logout


  get  'population'         => 'population_process#index',   as: :population_process_index
  post 'population/root'    => 'population_process#root',    as: :population_process_root
  post 'population/general' => 'population_process#general', as: :population_process_general
  post 'population/age_range'      => 'population_process#age_range',      as: :population_process_age_range
  post 'population/root_couple'    => 'population_process#root_couple',    as: :population_process_root_couple
  post 'population/general_couple' => 'population_process#general_couple', as: :population_process_general_couple

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)



  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :order
end

app/controllers/items_controller.rb
class ItemsController < Admin::ApplicationController
  layout 'admin'

  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:owner, :name, :price, :number, :is_paid, :order_id, :restaurant_id)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @item.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h4>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :owner, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :owner, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :price, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :price, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :number, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :number, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :is_paid, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.check_box :is_paid, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :order_id, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :order_id, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :restaurant_id, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :restaurant_id, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/items/edit.html.erb
<div class="page-header">
  <%= link_to items_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @item, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing item</h1>
</div>

<%= render 'form' %>

app/views/items/index.html.erb
<div class="page-header">
<!--
  <%= link_to new_item_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Item
  <% end %>
-->
  <h1>Listing items</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Owner</th>
            <th>Name</th>
            <th>Price</th>
            <th>Number</th>
            <th>Is paid</th>
            <th>Order</th>
            <th>Restaurant</th>
            <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @items) do |item| %>
            <td><%= item.owner %></td>
            <td><%= item.name %></td>
            <td><%= item.price %></td>
            <td><%= item.number %></td>
            <td><%= item.is_paid %></td>
            <td><%= item.order_id %></td>
            <td><%= item.restaurant_id %></td>
            <td class="text-right">
              <div class="btn-group" role="group" aria-label="...">
                <%= link_to 'Show', item, class:  "btn btn-default" %>
                <%= link_to 'Edit', edit_item_path(item), class:  "btn btn-default" %>
                <%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }, class:  "btn btn-default" %>
              </div>
            </td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/items/new.html.erb
<div class="page-header">
  <%= link_to items_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New item</h1>
</div>

<%= render 'form' %>

app/views/items/show.html.erb
<div class="page-header">
  <%= link_to items_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_item_path(@item), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show item</h1>
</div>

<dl class="dl-horizontal">
  <dt>Owner:</dt>
  <dd><%= @item.owner %></dd>

  <dt>Name:</dt>
  <dd><%= @item.name %></dd>

  <dt>Price:</dt>
  <dd><%= @item.price %></dd>

  <dt>Number:</dt>
  <dd><%= @item.number %></dd>

  <dt>Is paid:</dt>
  <dd><%= @item.is_paid %></dd>

  <dt>Order:</dt>
  <dd><%= @item.order_id %></dd>

  <dt>Restaurant:</dt>
  <dd><%= @item.restaurant_id %></dd>

</dl>