config/routes.rb
Rails.application.routes.draw do
  resources :orders do
    member do
      post 'open'
      post 'close'
    end
  end

  resources :items
  resources :restaurants

  root 'population_process#index'
  get  'admin' => 'admin#index', as: :admin

  post   'add_item'             => 'main#add_item',    as: :add_item
  delete 'delete_item/:item_id' => 'main#delete_item', as: :delete_item
  get    'typehead'             => 'main#typehead',    as: :typehead

  post 'user/login'  => 'user#login',    as: :user_login
  post 'user/logout' => 'user#logout',   as: :user_logout


  get  'population'         => 'population_process#index',   as: :population_process_index
  post 'population/root'    => 'population_process#root',    as: :population_process_root
  post 'population/general' => 'population_process#general', as: :population_process_general
  post 'population/age_range'      => 'population_process#age_range',      as: :population_process_age_range
  post 'population/root_couple'    => 'population_process#root_couple',    as: :population_process_root_couple
  post 'population/general_couple' => 'population_process#general_couple', as: :population_process_general_couple

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)



  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/population_process_controller.rb
class PopulationProcessController < ApplicationController
  def index

  end

  def root
    begin
      if !params[:population]
        flash[:error] = "抱歉，您沒有選擇檔案"
        redirect_to population_process_index_path
        return
      end

      upload_file = params[:population][:source_file]
      row_length = params[:population][:row_length]
      row_length = row_length ? row_length.to_i : nil

      hash = Digest::SHA256.hexdigest Time.now.to_s
      source_path = "tmp/#{hash}.csv"
      result_path = "tmp/#{hash}-result.csv"

      File.open(source_path, 'wb') do |f|
        f.write(upload_file.read)
      end

      c = CountryPopulationCalculator.new

      if c.run(source_path, result_path, row_length)
        send_file(result_path, filename: "結果-#{upload_file.original_filename}")
      else
        flash[:error] = "抱歉，處理時發生錯誤: 本檔案無法在有限時間找出解答"
        redirect_to population_process_index_path
      end
    rescue
      flash[:error] = "抱歉，處理時發生錯誤"
      redirect_to population_process_index_path
    end
  end

  def root_couple
    begin
      if !params[:population] || !params[:population][:source_file_male] || !params[:population][:source_file_female]
        flash[:error] = "抱歉，您沒有選擇檔案"
        redirect_to population_process_index_path
        return
      end

      upload_file_male = params[:population][:source_file_male]
      upload_file_female = params[:population][:source_file_female]

      row_length = params[:population][:row_length]
      row_length = row_length ? row_length.to_i : nil

      hash = Digest::SHA256.hexdigest Time.now.to_s

      source_male_path = "tmp/#{hash}-m.csv"
      source_female_path = "tmp/#{hash}-f.csv"

      result_male_path = "tmp/#{hash}-m-result.csv"
      result_female_path = "tmp/#{hash}-f-result.csv"
      result_zip_path  = "tmp/#{hash}-result.csv"

      File.open(source_male_path, 'wb') do |f|
        f.write(upload_file_male.read)
      end

      File.open(source_female_path, 'wb') do |f|
        f.write(upload_file_female.read)
      end

      c = CountryPopulationGenderBalanceCalculator.new

      if c.run(source_male_path, source_female_path, result_male_path, result_female_path, row_length)
        Zip::File.open(result_zip_path, Zip::File::CREATE) do |zipfile|
          zipfile.add("male.csv", result_male_path)
          zipfile.add("female.csv", result_female_path)
        end

        send_file(result_zip_path, filename: "結果.zip")
      else
        flash[:error] = "抱歉，處理時發生錯誤: 本檔案無法在有限時間找出解答"
        redirect_to population_process_index_path
      end
    rescue
      flash[:error] = "抱歉，處理時發生錯誤"
      redirect_to population_process_index_path
    end
  end

  def age_range
    begin
      if !params[:population] || !params[:population][:source_all_file] || !params[:population][:source_file_age_range]
        flash[:error] = "抱歉，您沒有選擇檔案"
        redirect_to population_process_index_path
        return
      end

      upload_file_all = params[:population][:source_all_file]
      upload_file_age_range = params[:population][:source_file_age_range]

      hash = Digest::SHA256.hexdigest Time.now.to_s

      source_all_path = "tmp/#{hash}-all.csv"
      source_age_range_path = "tmp/#{hash}-age-range.csv"

      result_path = "tmp/#{hash}-result.csv"

      File.open(source_all_path, 'wb') do |f|
        f.write(upload_file_all.read)
      end

      File.open(source_age_range_path, 'wb') do |f|
        f.write(upload_file_age_range.read)
      end

      c = CountryPopulationExpandAgeCalculator.new

      if c.run(source_age_range_path, source_all_path, result_path)
        send_file(result_path, filename: "結果-#{upload_file_age_range.original_filename}")
      else
        flash[:error] = "抱歉，處理時發生錯誤: 本檔案無法在有限時間找出解答"
        redirect_to population_process_index_path
      end
    rescue
      flash[:error] = "抱歉，處理時發生錯誤"
      redirect_to population_process_index_path
    end
  end

  def general
    begin
      if !params[:population]
        flash[:error] = "抱歉，您沒有選擇檔案"
        redirect_to population_process_index_path
        return
      end

      upload_file = params[:population][:source_file]
      row_length = params[:population][:row_length]
      row_length = row_length ? row_length.to_i : nil

      hash = Digest::SHA256.hexdigest Time.now.to_s
      source_path = "tmp/#{hash}.csv"
      result_path = "tmp/#{hash}-result.csv"

      File.open(source_path, 'wb') do |f|
        f.write(upload_file.read)
      end

      c = GeneralPopulationCalculator.new

      if c.run(source_path, result_path, row_length)
        send_file(result_path, filename: "結果-#{upload_file.original_filename}")
      else
        flash[:error] = "抱歉，處理時發生錯誤: 本檔案無法在有限時間找出解答"
        redirect_to population_process_index_path
      end
    rescue
      flash[:error] = "抱歉，處理時發生錯誤"
      redirect_to population_process_index_path
    end
  end

  def general_couple
    begin
      if !params[:population] || !params[:population][:source_file_male] || !params[:population][:source_file_female]
        flash[:error] = "抱歉，您沒有選擇檔案"
        redirect_to population_process_index_path
        return
      end

      upload_file_male = params[:population][:source_file_male]
      upload_file_female = params[:population][:source_file_female]

      row_length = params[:population][:row_length]
      row_length = row_length ? row_length.to_i : nil

      hash = Digest::SHA256.hexdigest Time.now.to_s

      source_male_path = "tmp/#{hash}-m.csv"
      source_female_path = "tmp/#{hash}-f.csv"

      result_male_path = "tmp/#{hash}-m-result.csv"
      result_female_path = "tmp/#{hash}-f-result.csv"
      result_zip_path  = "tmp/#{hash}-result.csv"

      File.open(source_male_path, 'wb') do |f|
        f.write(upload_file_male.read)
      end

      File.open(source_female_path, 'wb') do |f|
        f.write(upload_file_female.read)
      end

      c = GeneralPopulationGenderBalanceCalculator.new

      if c.run(source_male_path, source_female_path, result_male_path, result_female_path, row_length)
        Zip::File.open(result_zip_path, Zip::File::CREATE) do |zipfile|
          zipfile.add("male.csv", result_male_path)
          zipfile.add("female.csv", result_female_path)
        end

        send_file(result_zip_path, filename: "結果.zip")
      else
        flash[:error] = "抱歉，處理時發生錯誤: 本檔案無法在有限時間找出解答"
        redirect_to population_process_index_path
      end
    rescue
      flash[:error] = "抱歉，處理時發生錯誤"
      redirect_to population_process_index_path
    end
  end
end

app/helpers/population_process_helper.rb
module PopulationProcessHelper
end

app/views/population_process/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <a class="navbar-brand" href="<%= population_process_index_path %>">自動人口數目調整</a>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
    </div>
  </div>
</nav>

app/views/population_process/index.html.erb
<%= render partial: 'population_process/header' %>

<% if !browser.modern? %>
  <div class="container">
    <div class="jumbotron">
      <h2>Oops！抱歉，你的瀏覽器太舊了</h2>
      <p>請使用其他版本的瀏覽器，例如 Firefox 或 Chrome，謝謝</p>
    </div>
  </div>
<% else %>
  <% if flash[:error] %>
    <div class="alert alert-danger" role="alert"><%= flash[:error] %></div>
  <% end %>

  <div class="jumbotron">
    <h2>全台總表 (男女平衡)</h2>
    <p>範例上傳格式：
      <a href="/sample/男.csv" target="_blank">男</a> / <a href="/sample/女.csv" target="_blank">女</a>
    </p>
    <br />
    <%= form_for(:population, url: population_process_root_couple_path, html: { class: "form-inline", role: "form" }) do |f| %>
      <div class="form-group form-group">
        <lable>男</lable>
        <%= f.file_field :source_file_male, class: "form-control" %>
      </div>
      <div class="form-group form-group">
        <lable>女</lable>
        <%= f.file_field :source_file_female, class: "form-control" %>
      </div>
      <div class="form-group form-group">
        <lable>處理欄位數目</lable>
        <%= f.text_field :row_length, class: "form-control", type: 'number', value: 26 %>
      </div>
      <button type="submit" class="btn btn-primary btn">取得結果</button>
    <% end %>
  </div>

  <div class="jumbotron">
    <h2>全台年齡展開</h2>
    <p>範例上傳格式：
      <a href="/sample/男_結果.csv" target="_blank">男-總表結果</a> / <a href="/sample/男_年齡展開.csv" target="_blank">男-年齡展開</a>
    </p>
    <br />
    <%= form_for(:population, url: population_process_age_range_path, html: { class: "form-inline", role: "form" }) do |f| %>
      <div class="form-group form-group">
        <lable>男-總表結果</lable>
        <%= f.file_field :source_all_file, class: "form-control" %>
      </div>
      <div class="form-group form-group">
        <lable>男-年齡展開</lable>
        <%= f.file_field :source_file_age_range, class: "form-control" %>
      </div>
      <button type="submit" class="btn btn-primary btn">取得結果</button>
    <% end %>
  </div>

  <div class="jumbotron">
    <h2>縣市轉換 (男女平衡)</h2>
    <p>範例上傳格式：
      <a href="/sample/男_連江縣.csv" target="_blank">男-連江縣</a>/
      <a href="/sample/女_連江縣.csv" target="_blank">女-連江縣</a>
    </p>
    <p>* 第一列必須是 “指定首行總計”，給訂資料的總計列的細項須進位或退位</p>
    <br />
    <%= form_for(:population, url: population_process_general_couple_path, html: { class: "form-inline", role: "form" }) do |f| %>
      <div class="form-group form-group">
        <lable>男</lable>
        <%= f.file_field :source_file_male, class: "form-control" %>
      </div>
      <div class="form-group form-group">
        <lable>女</lable>
        <%= f.file_field :source_file_female, class: "form-control" %>
      </div>
      <div class="form-group form-group">
        <lable>處理欄位數目</lable>
        <%= f.text_field :row_length, class: "form-control", type: 'number', value: 26 %>
      </div>
      <button type="submit" class="btn btn-primary btn">取得結果</button>
    <% end %>
  </div>

  <div class="jumbotron">
    <h2>通用型轉換</h2>
    <p>範例上傳格式：<a href="/sample/女_連江縣.csv" target="_blank">下載</a></p>
    <p>* 第一列必須是 “指定首行總計”，給訂資料的總計列的細項須進位或退位</p>
    <br />
    <%= form_for(:population, url: population_process_general_path, html: { class: "form-inline", role: "form" }) do |f| %>
      <div class="form-group form-group">
        <%= f.file_field :source_file, class: "form-control" %>
      </div>
      <div class="form-group form-group">
        <lable>處理欄位數目</lable>
        <%= f.text_field :row_length, class: "form-control", type: 'number', value: 26 %>
      </div>
      <button type="submit" class="btn btn-primary btn">取得結果</button>
    <% end %>
  </div>
<% end %>